package exampleM3;

import exampleM3.model.EmpM3;
import exampleM3.model.EmpExampleM3;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpMapperM3 {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Wed Oct 11 18:38:50 CST 2023
     */
    long countByExample(EmpExampleM3 example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Wed Oct 11 18:38:50 CST 2023
     */
    int deleteByExample(EmpExampleM3 example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Wed Oct 11 18:38:50 CST 2023
     */
    int insert(EmpM3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Wed Oct 11 18:38:50 CST 2023
     */
    int insertSelective(EmpM3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Wed Oct 11 18:38:50 CST 2023
     */
    List<EmpM3> selectByExample(EmpExampleM3 example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Wed Oct 11 18:38:50 CST 2023
     */
    int updateByExampleSelective(@Param("record") EmpM3 record, @Param("example") EmpExampleM3 example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Wed Oct 11 18:38:50 CST 2023
     */
    int updateByExample(@Param("record") EmpM3 record, @Param("example") EmpExampleM3 example);
}