package exampleSimple.mapper;

import exampleSimple.model.EmpSimple;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface EmpMapperSimple {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Wed Oct 11 21:13:55 CST 2023
     */
    @Insert({
        "insert into SCOTT.EMP (EMPNO, ENAME, ",
        "JOB, MGR, HIREDATE, ",
        "SAL, COMM, DEPTNO)",
        "values (#{empno,jdbcType=NUMERIC}, #{ename,jdbcType=VARCHAR}, ",
        "#{job,jdbcType=VARCHAR}, #{mgr,jdbcType=NUMERIC}, #{hiredate,jdbcType=TIMESTAMP}, ",
        "#{sal,jdbcType=NUMERIC}, #{comm,jdbcType=NUMERIC}, #{deptno,jdbcType=NUMERIC})"
    })
    int insert(EmpSimple record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Wed Oct 11 21:13:55 CST 2023
     */
    @Select({
        "select",
        "EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO",
        "from SCOTT.EMP"
    })
    @Results({
        @Result(column="EMPNO", property="empno", jdbcType=JdbcType.NUMERIC),
        @Result(column="ENAME", property="ename", jdbcType=JdbcType.VARCHAR),
        @Result(column="JOB", property="job", jdbcType=JdbcType.VARCHAR),
        @Result(column="MGR", property="mgr", jdbcType=JdbcType.NUMERIC),
        @Result(column="HIREDATE", property="hiredate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="SAL", property="sal", jdbcType=JdbcType.NUMERIC),
        @Result(column="COMM", property="comm", jdbcType=JdbcType.NUMERIC),
        @Result(column="DEPTNO", property="deptno", jdbcType=JdbcType.NUMERIC)
    })
    List<EmpSimple> selectAll();
}